#This macro can not be executed standalone

/DRsim/action/useHepMC False
/DRsim/action/useCalib False

/vis/disable
/run/numberOfThreads 1
/run/initialize
/run/verbose 1

/DRsim/generator/theta 90.
/DRsim/generator/phi 90.

/DRsim/generator/x0 0
/DRsim/generator/y0 -10
/DRsim/generator/z0 0

/DRsim/generator/randx 10 mm
/DRsim/generator/randy 0
/DRsim/generator/randz 10 mm

/gun/particle proton
/gun/energy 400 MeV
/run/beamOn 10

