#This macro can not be executed standalone

/DRsim/action/useHepMC False
/DRsim/action/useCalib False

/vis/disable
/run/numberOfThreads 1
/run/initialize
/run/verbose 1

/DRsim/generator/theta 90.
/DRsim/generator/phi 90.

/DRsim/generator/x0 0 mm
/DRsim/generator/y0 -10 cm
/DRsim/generator/z0 0 mm

/DRsim/generator/randx 1 cm
/DRsim/generator/randy 0 cm
/DRsim/generator/randz 1 cm

/gun/particle ion
/gun/ion 6 12 0 0
/gun/energy 400 MeV
/run/beamOn 10

