#include "RootInterface.h"
#include "RecoInterface.h"
#include "DRsimInterface.h"
#include "functions.h"

#include "TROOT.h"
#include "TStyle.h"
#include "TH1.h"
#include "TH2.h"
#include "TCanvas.h"
#include "TF1.h"
#include "TPaveStats.h"
#include "TString.h"
#include "TLorentzVector.h"
#include "TGraph.h"

#include <iostream>
#include <string>

int main(int argc, char* argv[]) {
  TString filename = argv[1];
  TString outputname = argv[2];

  gStyle->SetOptFit(1);

  RootInterface<DRsimInterface::DRsimEventData>* drInterface = new RootInterface<DRsimInterface::DRsimEventData>(std::string(filename), false);
  drInterface->GetChain("DRsim");

  TH1F* tEdep = new TH1F("totEdep","Total Energy deposit;MeV;Evt",100,0.,2.);
  tEdep->Sumw2(); tEdep->SetLineColor(kRed); tEdep->SetLineWidth(2);
  TH1F* tHit_C = new TH1F("Hit_C","# of p.e. of Cerenkov ch.;# of p.e.;Evt",100,0,100.);
  tHit_C->Sumw2(); tHit_C->SetLineColor(kBlue); tHit_C->SetLineWidth(2);
  TH1F* tHit_S = new TH1F("Hit_S","# of p.e. of Scintillation ch.;# of p.e.;Evt",300,0,300);
  tHit_S->Sumw2(); tHit_S->SetLineColor(kRed); tHit_S->SetLineWidth(2);

  TH1F* tT_C = new TH1F("time_C","Cerenkov time;ns;p.e.",600,10.,70.);
  tT_C->Sumw2(); tT_C->SetLineColor(kBlue); tT_C->SetLineWidth(2);
  TH1F* tT_S = new TH1F("time_S","Scint time;ns;p.e.",600,10.,70.);
  tT_S->Sumw2(); tT_S->SetLineColor(kRed); tT_S->SetLineWidth(2);
  TH1F* tWav_S = new TH1F("wavlen_S","Scint wavelength;nm;p.e.",120,300.,900.);
  tWav_S->Sumw2(); tWav_S->SetLineColor(kRed); tWav_S->SetLineWidth(2);
  TH1F* tWav_C = new TH1F("wavlen_C","Cerenkov wavelength;nm;p.e.",120,300.,900.);
  tWav_C->Sumw2(); tWav_C->SetLineColor(kBlue); tWav_C->SetLineWidth(2);
  TH1F* tNhit_S = new TH1F("nHits_S","Number of Scint p.e./SiPM;p.e.;n",200,0.,200.);
  tNhit_S->Sumw2(); tNhit_S->SetLineColor(kRed); tNhit_S->SetLineWidth(2);
  TH1F* tNhit_C = new TH1F("nHits_C","Number of Cerenkov p.e./SiPM;p.e.;n",50,0.,50.);
  tNhit_C->Sumw2(); tNhit_C->SetLineColor(kBlue); tNhit_C->SetLineWidth(2);

  TH1F* tSOptical = new TH1F("scint optical","Number optical photon generated by Scint;number of optical photon;evt",200,0,12000);
  tSOptical->Sumw2(); tSOptical->SetLineColor(kRed); tSOptical->SetLineWidth(2);
  TH1F* tCOptical = new TH1F("ceren optical","Number optical photon generated by Ceren;number of optical photon;evt",100,0,300);
  tCOptical->Sumw2(); tCOptical->SetLineColor(kBlue); tCOptical->SetLineWidth(2);
  
  unsigned int entries = drInterface->entries();
  std::cout << drInterface->entries() << std::endl;
  int tol_s=0; int tol_c=0;
  int tol2_s=0; int tol2_c=0;
  while (drInterface->numEvt() < entries) {
    if (drInterface->numEvt() % 100 == 0) printf("Analyzing %dth event ...\n", drInterface->numEvt());

    DRsimInterface::DRsimEventData drEvt;
    drInterface->read(drEvt);

    float Edep = 0.;
    for (auto edepItr = drEvt.Edeps.begin(); edepItr != drEvt.Edeps.end(); ++edepItr) {
      auto edep = *edepItr;
      Edep += edep.Edep;
    }
    tEdep->Fill(Edep);
    int SOptical=0;
    int COptical=0;
    for (auto photonIter =drEvt.opticalPhotons.begin();photonIter != drEvt.opticalPhotons.end();++photonIter){
      auto Photon = *photonIter;
      SOptical = Photon.scintOpticalPhotonNumber; 
      COptical = Photon.cerenOpticalPhotonNumber; 
    }
    //if(SOptical!=0)tSOptical->Fill(SOptical);
    //if(COptical!=0)tCOptical->Fill(COptical);
    //if(Edep>1.3)tSOptical->Fill(SOptical);
    //if(Edep>1.3)tCOptical->Fill(COptical);
    if(tol_s<SOptical) tol_s = SOptical;
    if(tol_c<COptical) tol_c = COptical;
    tSOptical->Fill(SOptical);
    tCOptical->Fill(COptical);

    // float Pleak = 0.;
    // float Eleak_nu = 0.;
    // for (auto leak : drEvt.leaks) {
    //   TLorentzVector leak4vec;
    //   leak4vec.SetPxPyPzE(leak.px,leak.py,leak.pz,leak.E);
    //   if ( std::abs(leak.pdgId)==12 || std::abs(leak.pdgId)==14 || std::abs(leak.pdgId)==16 ) {
    //     Eleak_nu += leak4vec.P();
    //   } else {
    //     Pleak += leak4vec.P();
    //   }
    // }
    // tP_leak->Fill(Pleak);
    // tP_leak_nu->Fill(Eleak_nu);

    int nHitC = 0; int nHitS = 0;
    for (auto tower = drEvt.towers.begin(); tower != drEvt.towers.end(); ++tower) {
      int moduleNum = tower->ModuleNum;
      for (auto sipm = tower->SiPMs.begin(); sipm != tower->SiPMs.end(); ++sipm) {
        int plateNum = sipm->x; int fiberNum = sipm->y; 
        if ( RecoInterface::IsCerenkov(sipm->x,sipm->y) ) {
          tNhit_C->Fill(sipm->count);
          for (const auto timepair : sipm->timeStruct) {
            tT_C->Fill(timepair.first.first+0.05,timepair.second);
            nHitC += timepair.second;

            // if (timepair.first.first < 35) {
            //   nHitC += timepair.second;
            //   // t2DhitC->Fill(60*(moduleNum%7)+fiberNum, 60*(moduleNum/7)+plateNum, timepair.second);
            // }
          }
          for (const auto wavpair : sipm->wavlenSpectrum) {
            tWav_C->Fill(wavpair.first.first,wavpair.second);
          }
        } else {
          tNhit_S->Fill(sipm->count);
          nHitS += sipm->count;
          // t2DhitS->Fill(60*(moduleNum%7)+fiberNum, 60*(moduleNum/7)+plateNum, sipm->count);
          for (const auto timepair : sipm->timeStruct) {
            tT_S->Fill(timepair.first.first+0.05,timepair.second);
          }
          for (const auto wavpair : sipm->wavlenSpectrum) {
            tWav_S->Fill(wavpair.first.first,wavpair.second);
          }
        }
      }
    }
    if(tol2_s<nHitS) tol2_s = nHitS;
    if(tol2_c<nHitC) tol2_c = nHitC;

    tHit_C->Fill(nHitC);
    tHit_S->Fill(nHitS);
  } // event loop
  // drInterface->close();
  std::cout<<"the mas value is S op "<<tol_s<<std::endl;
  std::cout<<"the mas value is C op "<<tol_c<<std::endl;
  std::cout<<"the mas value is S hit "<<tol2_s<<std::endl;
  std::cout<<"the mas value is C hit "<<tol2_c<<std::endl;
  TFile *f = new TFile(outputname+".root","recreate");
  tEdep->SetOption("hist");
  tEdep->Write();
  tHit_C->SetOption("hist");
  tHit_S->SetOption("hist");
  tHit_C->Write();
  tHit_S->Write();



  tT_C->Write();
  tT_S->Write();
  tWav_C->Write();
  tWav_S->Write();
  tNhit_C->SetOption("hist");
  tNhit_S->SetOption("hist");
  tNhit_C->Write();
  tNhit_S->Write();

  tCOptical->SetOption("hist");
  tSOptical->SetOption("hist");
  tCOptical->Write();
  tSOptical->Write();
  f->Close();
}

